// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protos/methods.proto

package anomalydetector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleAnomalyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sample float64 `protobuf:"fixed64,1,opt,name=sample,proto3" json:"sample,omitempty"`
}

func (x *SingleAnomalyRequest) Reset() {
	*x = SingleAnomalyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_methods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleAnomalyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleAnomalyRequest) ProtoMessage() {}

func (x *SingleAnomalyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_methods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleAnomalyRequest.ProtoReflect.Descriptor instead.
func (*SingleAnomalyRequest) Descriptor() ([]byte, []int) {
	return file_protos_methods_proto_rawDescGZIP(), []int{0}
}

func (x *SingleAnomalyRequest) GetSample() float64 {
	if x != nil {
		return x.Sample
	}
	return 0
}

type AnomalyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnomalousValues []float64 `protobuf:"fixed64,1,rep,packed,name=anomalous_values,json=anomalousValues,proto3" json:"anomalous_values,omitempty"`
}

func (x *AnomalyResponse) Reset() {
	*x = AnomalyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_methods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnomalyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyResponse) ProtoMessage() {}

func (x *AnomalyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_methods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyResponse.ProtoReflect.Descriptor instead.
func (*AnomalyResponse) Descriptor() ([]byte, []int) {
	return file_protos_methods_proto_rawDescGZIP(), []int{1}
}

func (x *AnomalyResponse) GetAnomalousValues() []float64 {
	if x != nil {
		return x.AnomalousValues
	}
	return nil
}

var File_protos_methods_proto protoreflect.FileDescriptor

var file_protos_methods_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x2e,
	0x0a, 0x14, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x3c,
	0x0a, 0x0f, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x6f, 0x75, 0x73, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0f, 0x61, 0x6e, 0x6f,
	0x6d, 0x61, 0x6c, 0x6f, 0x75, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0x5d, 0x0a, 0x0f,
	0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x4a, 0x0a, 0x0d, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x63, 0x61, 0x72, 0x64,
	0x69, 0x61, 0x6e, 0x31, 0x34, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64,
	0x6f, 0x73, 0x2f, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_methods_proto_rawDescOnce sync.Once
	file_protos_methods_proto_rawDescData = file_protos_methods_proto_rawDesc
)

func file_protos_methods_proto_rawDescGZIP() []byte {
	file_protos_methods_proto_rawDescOnce.Do(func() {
		file_protos_methods_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_methods_proto_rawDescData)
	})
	return file_protos_methods_proto_rawDescData
}

var file_protos_methods_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_methods_proto_goTypes = []interface{}{
	(*SingleAnomalyRequest)(nil), // 0: protos.SingleAnomalyRequest
	(*AnomalyResponse)(nil),      // 1: protos.AnomalyResponse
}
var file_protos_methods_proto_depIdxs = []int32{
	0, // 0: protos.AnomalyDetector.DetectAnomaly:input_type -> protos.SingleAnomalyRequest
	1, // 1: protos.AnomalyDetector.DetectAnomaly:output_type -> protos.AnomalyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_methods_proto_init() }
func file_protos_methods_proto_init() {
	if File_protos_methods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_methods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleAnomalyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_methods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnomalyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_methods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_methods_proto_goTypes,
		DependencyIndexes: file_protos_methods_proto_depIdxs,
		MessageInfos:      file_protos_methods_proto_msgTypes,
	}.Build()
	File_protos_methods_proto = out.File
	file_protos_methods_proto_rawDesc = nil
	file_protos_methods_proto_goTypes = nil
	file_protos_methods_proto_depIdxs = nil
}
