/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CUENTA_H_RPCGEN
#define _CUENTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int x;
	int y;
};
typedef struct operands operands;

#define CUENTA 0x20000001
#define CUENTA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(operands *, CLIENT *);
extern  int * suma_1_svc(operands *, struct svc_req *);
#define RESTA 2
extern  int * resta_1(operands *, CLIENT *);
extern  int * resta_1_svc(operands *, struct svc_req *);
extern int cuenta_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
extern int cuenta_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CUENTA_H_RPCGEN */
