/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cuenta.h"

int *
suma_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	int x = argp->x;
	int y = argp->y;
	
	result = x + y;

	return &result;
}

int *
resta_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	int x = argp->x;
	int y = argp->y;
	
	result = x - y;

	return &result;
}
