/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CuentaSencilla;
import io.grpc.Server;
import io.grpc.ServerBuilder;


import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, InterruptedException{
        Server server = ServerBuilder.forPort(9000).addService(new Services()).build();
        server.start();
        System.out.println("Server started on: "+server.getPort());
        server.awaitTermination();
    }
}
